.

diff --git a/.github/workflows/pypi.yml b/.github/workflows/pypi.yml
--- a/.github/workflows/pypi.yml
+++ b/.github/workflows/pypi.yml
@@ -10,7 +10,7 @@ on:
 
 jobs:
   manylinux:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     steps:
     - uses: actions/checkout@v3
       with:
@@ -99,13 +99,13 @@ jobs:
         echo "install_lib=" >> python/setup.cfg
     - name: Build deps and library
       run: |
-        sudo chmod +x tools/build_macos_10_9.sh
-        tools/build_macos_10_9.sh || { echo "Build command failed."; exit 1; }
+        sudo chmod +x tools/build_macos_11.sh
+        tools/build_macos_11.sh || { echo "Build command failed."; exit 1; }
     - name: Build wheel
       run: |
         cd python
         python setup.py bdist_wheel
-        find ./dist/ -type f -iname "decord*.whl" -exec sh -c 'mv $0 ${0/\10_14/10_9}' {} \;
+        find ./dist/ -type f -iname "decord*.whl" -exec sh -c 'mv $0 ${0/\10_14/11}' {} \;
     - name: Fix wheel by delocate
       run: |
         FFMPEG_DIR="$HOME"/ffmpeg_build
