.

diff --git a/.github/workflows/pypi.yml b/.github/workflows/pypi.yml
--- a/.github/workflows/pypi.yml
+++ b/.github/workflows/pypi.yml
@@ -99,13 +99,13 @@ jobs:
         echo "install_lib=" >> python/setup.cfg
     - name: Build deps and library
       run: |
-        sudo chmod +x tools/build_macos_12.5.sh
-        tools/build_macos_12.5.sh || { echo "Build command failed."; exit 1; }
+        sudo chmod +x tools/build_macos_12_5.sh
+        tools/build_macos_12_5.sh || { echo "Build command failed."; exit 1; }
     - name: Build wheel
       run: |
         cd python
         python setup.py bdist_wheel
-        find ./dist/ -type f -iname "decord*.whl" -exec sh -c 'mv $0 ${0/\10_14/12.5}' {} \;
+        find ./dist/ -type f -iname "decord*.whl" -exec sh -c 'mv $0 ${0/\10_14/12_5}' {} \;
     - name: Fix wheel by delocate
       run: |
         FFMPEG_DIR="$HOME"/ffmpeg_build
